# Generated by Django 3.2 on 2021-09-16 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='GenericCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название будет автоматически переведено в нижний регистр для корректной работы поиска', max_length=220, verbose_name='Название товара')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('discription', models.TextField(verbose_name='Описание товара')),
                ('slug', models.SlugField(unique=True)),
                ('sex', models.CharField(choices=[('М', 'Мужчины'), ('Ж', 'Женщины'), ('У', 'Унисекс')], default=('У', 'Унисекс'), max_length=1, verbose_name='Пол')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Цена товара')),
                ('material', models.CharField(max_length=300, verbose_name='Материал')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_presence', models.BooleanField(default=True, verbose_name='Наличие')),
                ('categories', models.ManyToManyField(to='shop.GenericCategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Обувь',
                'verbose_name_plural': 'Обувь',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual', models.SmallIntegerField(null=True, verbose_name='Внешний вид')),
                ('quality', models.SmallIntegerField(null=True, verbose_name='Качество')),
                ('price', models.SmallIntegerField(null=True, verbose_name='Цена')),
                ('convenience', models.SmallIntegerField(null=True, verbose_name='Удобство')),
                ('set_date', models.DateTimeField(auto_now_add=True, verbose_name='Время выставления оценки')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='shop.comment')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название будет автоматически переведено в нижний регистр для корректной работы поиска', max_length=220, verbose_name='Название товара')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('discription', models.TextField(verbose_name='Описание товара')),
                ('slug', models.SlugField(unique=True)),
                ('sex', models.CharField(choices=[('М', 'Мужчины'), ('Ж', 'Женщины'), ('У', 'Унисекс')], default=('У', 'Унисекс'), max_length=1, verbose_name='Пол')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Цена товара')),
                ('material', models.CharField(max_length=300, verbose_name='Материал')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_presence', models.BooleanField(default=True, verbose_name='Наличие')),
                ('categories', models.ManyToManyField(to='shop.GenericCategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежда',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mark', to='shop.mark', verbose_name='Оценка'),
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название будет автоматически переведено в нижний регистр для корректной работы поиска', max_length=220, verbose_name='Название товара')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('discription', models.TextField(verbose_name='Описание товара')),
                ('slug', models.SlugField(unique=True)),
                ('sex', models.CharField(choices=[('М', 'Мужчины'), ('Ж', 'Женщины'), ('У', 'Унисекс')], default=('У', 'Унисекс'), max_length=1, verbose_name='Пол')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Цена товара')),
                ('material', models.CharField(max_length=300, verbose_name='Материал')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_presence', models.BooleanField(default=True, verbose_name='Наличие')),
                ('categories', models.ManyToManyField(to='shop.GenericCategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': 'Аксессуары',
            },
        ),
    ]
