# Generated by Django 3.2 on 2021-10-09 16:46

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name': 'Аксессуары', 'verbose_name_plural': 'Аксессуары'},
        ),
        migrations.AddField(
            model_name='accessory',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video', verbose_name='Видео обзор'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Ссылка на видео обзор'),
        ),
        migrations.AddField(
            model_name='garment',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video', verbose_name='Видео обзор'),
        ),
        migrations.AddField(
            model_name='garment',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Ссылка на видео обзор'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video', verbose_name='Видео обзор'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Ссылка на видео обзор'),
        ),
    ]
