# Generated by Django 3.2 on 2021-09-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210916_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
